/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVirksomhederRouteImport } from './routes/_authenticated/virksomheder'
import { Route as AuthenticatedSalgsmulighederRouteImport } from './routes/_authenticated/salgsmuligheder'
import { Route as AuthenticatedSalgsintelligensRouteImport } from './routes/_authenticated/salgsintelligens'
import { Route as AuthenticatedKontaktlisterRouteImport } from './routes/_authenticated/kontaktlister'
import { Route as AuthenticatedKonkurrenterRouteImport } from './routes/_authenticated/konkurrenter'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAftalerIndexRouteImport } from './routes/_authenticated/aftaler.index'
import { Route as AuthenticatedVirksomhederIdRouteImport } from './routes/_authenticated/virksomheder_.$id'
import { Route as AuthenticatedKontaktlisterIdRouteImport } from './routes/_authenticated/kontaktlister_.$id'
import { Route as AuthenticatedAftalerIdRouteImport } from './routes/_authenticated/aftaler.$id'
import { Route as AuthenticatedAdminOverblikRouteImport } from './routes/_authenticated/admin.overblik'
import { Route as AuthenticatedAdminImporthistorikRouteImport } from './routes/_authenticated/admin.importhistorik'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminCvrDebugRouteImport } from './routes/_authenticated/admin.cvr-debug'
import { Route as AuthenticatedAdminBrugereRouteImport } from './routes/_authenticated/admin.brugere'
import { Route as AuthenticatedAdminImportIndexRouteImport } from './routes/_authenticated/admin.import.index'
import { Route as AuthenticatedAdminImportVismaRouteImport } from './routes/_authenticated/admin.import.visma'
import { Route as AuthenticatedAdminImportMaskindataRouteImport } from './routes/_authenticated/admin.import.maskindata'
import { Route as AuthenticatedAdminImportCvrRouteImport } from './routes/_authenticated/admin.import.cvr'
import { Route as AuthenticatedAdminImportAndenRouteImport } from './routes/_authenticated/admin.import.anden'
import { Route as AuthenticatedAdminImportAftaleEmnerRouteImport } from './routes/_authenticated/admin.import.aftale-emner'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVirksomhederRoute =
  AuthenticatedVirksomhederRouteImport.update({
    id: '/virksomheder',
    path: '/virksomheder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalgsmulighederRoute =
  AuthenticatedSalgsmulighederRouteImport.update({
    id: '/salgsmuligheder',
    path: '/salgsmuligheder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalgsintelligensRoute =
  AuthenticatedSalgsintelligensRouteImport.update({
    id: '/salgsintelligens',
    path: '/salgsintelligens',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontaktlisterRoute =
  AuthenticatedKontaktlisterRouteImport.update({
    id: '/kontaktlister',
    path: '/kontaktlister',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKonkurrenterRoute =
  AuthenticatedKonkurrenterRouteImport.update({
    id: '/konkurrenter',
    path: '/konkurrenter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAftalerIndexRoute =
  AuthenticatedAftalerIndexRouteImport.update({
    id: '/aftaler/',
    path: '/aftaler/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVirksomhederIdRoute =
  AuthenticatedVirksomhederIdRouteImport.update({
    id: '/virksomheder_/$id',
    path: '/virksomheder/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontaktlisterIdRoute =
  AuthenticatedKontaktlisterIdRouteImport.update({
    id: '/kontaktlister_/$id',
    path: '/kontaktlister/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAftalerIdRoute = AuthenticatedAftalerIdRouteImport.update({
  id: '/aftaler/$id',
  path: '/aftaler/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminOverblikRoute =
  AuthenticatedAdminOverblikRouteImport.update({
    id: '/admin/overblik',
    path: '/admin/overblik',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminImporthistorikRoute =
  AuthenticatedAdminImporthistorikRouteImport.update({
    id: '/admin/importhistorik',
    path: '/admin/importhistorik',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCvrDebugRoute =
  AuthenticatedAdminCvrDebugRouteImport.update({
    id: '/admin/cvr-debug',
    path: '/admin/cvr-debug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBrugereRoute =
  AuthenticatedAdminBrugereRouteImport.update({
    id: '/admin/brugere',
    path: '/admin/brugere',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminImportIndexRoute =
  AuthenticatedAdminImportIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminImportRoute,
  } as any)
const AuthenticatedAdminImportVismaRoute =
  AuthenticatedAdminImportVismaRouteImport.update({
    id: '/visma',
    path: '/visma',
    getParentRoute: () => AuthenticatedAdminImportRoute,
  } as any)
const AuthenticatedAdminImportMaskindataRoute =
  AuthenticatedAdminImportMaskindataRouteImport.update({
    id: '/maskindata',
    path: '/maskindata',
    getParentRoute: () => AuthenticatedAdminImportRoute,
  } as any)
const AuthenticatedAdminImportCvrRoute =
  AuthenticatedAdminImportCvrRouteImport.update({
    id: '/cvr',
    path: '/cvr',
    getParentRoute: () => AuthenticatedAdminImportRoute,
  } as any)
const AuthenticatedAdminImportAndenRoute =
  AuthenticatedAdminImportAndenRouteImport.update({
    id: '/anden',
    path: '/anden',
    getParentRoute: () => AuthenticatedAdminImportRoute,
  } as any)
const AuthenticatedAdminImportAftaleEmnerRoute =
  AuthenticatedAdminImportAftaleEmnerRouteImport.update({
    id: '/aftale-emner',
    path: '/aftale-emner',
    getParentRoute: () => AuthenticatedAdminImportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/konkurrenter': typeof AuthenticatedKonkurrenterRoute
  '/kontaktlister': typeof AuthenticatedKontaktlisterRoute
  '/salgsintelligens': typeof AuthenticatedSalgsintelligensRoute
  '/salgsmuligheder': typeof AuthenticatedSalgsmulighederRoute
  '/virksomheder': typeof AuthenticatedVirksomhederRoute
  '/admin/brugere': typeof AuthenticatedAdminBrugereRoute
  '/admin/cvr-debug': typeof AuthenticatedAdminCvrDebugRoute
  '/admin/import': typeof AuthenticatedAdminImportRouteWithChildren
  '/admin/importhistorik': typeof AuthenticatedAdminImporthistorikRoute
  '/admin/overblik': typeof AuthenticatedAdminOverblikRoute
  '/aftaler/$id': typeof AuthenticatedAftalerIdRoute
  '/kontaktlister/$id': typeof AuthenticatedKontaktlisterIdRoute
  '/virksomheder/$id': typeof AuthenticatedVirksomhederIdRoute
  '/aftaler/': typeof AuthenticatedAftalerIndexRoute
  '/admin/import/aftale-emner': typeof AuthenticatedAdminImportAftaleEmnerRoute
  '/admin/import/anden': typeof AuthenticatedAdminImportAndenRoute
  '/admin/import/cvr': typeof AuthenticatedAdminImportCvrRoute
  '/admin/import/maskindata': typeof AuthenticatedAdminImportMaskindataRoute
  '/admin/import/visma': typeof AuthenticatedAdminImportVismaRoute
  '/admin/import/': typeof AuthenticatedAdminImportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/konkurrenter': typeof AuthenticatedKonkurrenterRoute
  '/kontaktlister': typeof AuthenticatedKontaktlisterRoute
  '/salgsintelligens': typeof AuthenticatedSalgsintelligensRoute
  '/salgsmuligheder': typeof AuthenticatedSalgsmulighederRoute
  '/virksomheder': typeof AuthenticatedVirksomhederRoute
  '/admin/brugere': typeof AuthenticatedAdminBrugereRoute
  '/admin/cvr-debug': typeof AuthenticatedAdminCvrDebugRoute
  '/admin/importhistorik': typeof AuthenticatedAdminImporthistorikRoute
  '/admin/overblik': typeof AuthenticatedAdminOverblikRoute
  '/aftaler/$id': typeof AuthenticatedAftalerIdRoute
  '/kontaktlister/$id': typeof AuthenticatedKontaktlisterIdRoute
  '/virksomheder/$id': typeof AuthenticatedVirksomhederIdRoute
  '/aftaler': typeof AuthenticatedAftalerIndexRoute
  '/admin/import/aftale-emner': typeof AuthenticatedAdminImportAftaleEmnerRoute
  '/admin/import/anden': typeof AuthenticatedAdminImportAndenRoute
  '/admin/import/cvr': typeof AuthenticatedAdminImportCvrRoute
  '/admin/import/maskindata': typeof AuthenticatedAdminImportMaskindataRoute
  '/admin/import/visma': typeof AuthenticatedAdminImportVismaRoute
  '/admin/import': typeof AuthenticatedAdminImportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/konkurrenter': typeof AuthenticatedKonkurrenterRoute
  '/_authenticated/kontaktlister': typeof AuthenticatedKontaktlisterRoute
  '/_authenticated/salgsintelligens': typeof AuthenticatedSalgsintelligensRoute
  '/_authenticated/salgsmuligheder': typeof AuthenticatedSalgsmulighederRoute
  '/_authenticated/virksomheder': typeof AuthenticatedVirksomhederRoute
  '/_authenticated/admin/brugere': typeof AuthenticatedAdminBrugereRoute
  '/_authenticated/admin/cvr-debug': typeof AuthenticatedAdminCvrDebugRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRouteWithChildren
  '/_authenticated/admin/importhistorik': typeof AuthenticatedAdminImporthistorikRoute
  '/_authenticated/admin/overblik': typeof AuthenticatedAdminOverblikRoute
  '/_authenticated/aftaler/$id': typeof AuthenticatedAftalerIdRoute
  '/_authenticated/kontaktlister_/$id': typeof AuthenticatedKontaktlisterIdRoute
  '/_authenticated/virksomheder_/$id': typeof AuthenticatedVirksomhederIdRoute
  '/_authenticated/aftaler/': typeof AuthenticatedAftalerIndexRoute
  '/_authenticated/admin/import/aftale-emner': typeof AuthenticatedAdminImportAftaleEmnerRoute
  '/_authenticated/admin/import/anden': typeof AuthenticatedAdminImportAndenRoute
  '/_authenticated/admin/import/cvr': typeof AuthenticatedAdminImportCvrRoute
  '/_authenticated/admin/import/maskindata': typeof AuthenticatedAdminImportMaskindataRoute
  '/_authenticated/admin/import/visma': typeof AuthenticatedAdminImportVismaRoute
  '/_authenticated/admin/import/': typeof AuthenticatedAdminImportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/konkurrenter'
    | '/kontaktlister'
    | '/salgsintelligens'
    | '/salgsmuligheder'
    | '/virksomheder'
    | '/admin/brugere'
    | '/admin/cvr-debug'
    | '/admin/import'
    | '/admin/importhistorik'
    | '/admin/overblik'
    | '/aftaler/$id'
    | '/kontaktlister/$id'
    | '/virksomheder/$id'
    | '/aftaler/'
    | '/admin/import/aftale-emner'
    | '/admin/import/anden'
    | '/admin/import/cvr'
    | '/admin/import/maskindata'
    | '/admin/import/visma'
    | '/admin/import/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/konkurrenter'
    | '/kontaktlister'
    | '/salgsintelligens'
    | '/salgsmuligheder'
    | '/virksomheder'
    | '/admin/brugere'
    | '/admin/cvr-debug'
    | '/admin/importhistorik'
    | '/admin/overblik'
    | '/aftaler/$id'
    | '/kontaktlister/$id'
    | '/virksomheder/$id'
    | '/aftaler'
    | '/admin/import/aftale-emner'
    | '/admin/import/anden'
    | '/admin/import/cvr'
    | '/admin/import/maskindata'
    | '/admin/import/visma'
    | '/admin/import'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/konkurrenter'
    | '/_authenticated/kontaktlister'
    | '/_authenticated/salgsintelligens'
    | '/_authenticated/salgsmuligheder'
    | '/_authenticated/virksomheder'
    | '/_authenticated/admin/brugere'
    | '/_authenticated/admin/cvr-debug'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/importhistorik'
    | '/_authenticated/admin/overblik'
    | '/_authenticated/aftaler/$id'
    | '/_authenticated/kontaktlister_/$id'
    | '/_authenticated/virksomheder_/$id'
    | '/_authenticated/aftaler/'
    | '/_authenticated/admin/import/aftale-emner'
    | '/_authenticated/admin/import/anden'
    | '/_authenticated/admin/import/cvr'
    | '/_authenticated/admin/import/maskindata'
    | '/_authenticated/admin/import/visma'
    | '/_authenticated/admin/import/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/virksomheder': {
      id: '/_authenticated/virksomheder'
      path: '/virksomheder'
      fullPath: '/virksomheder'
      preLoaderRoute: typeof AuthenticatedVirksomhederRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salgsmuligheder': {
      id: '/_authenticated/salgsmuligheder'
      path: '/salgsmuligheder'
      fullPath: '/salgsmuligheder'
      preLoaderRoute: typeof AuthenticatedSalgsmulighederRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salgsintelligens': {
      id: '/_authenticated/salgsintelligens'
      path: '/salgsintelligens'
      fullPath: '/salgsintelligens'
      preLoaderRoute: typeof AuthenticatedSalgsintelligensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kontaktlister': {
      id: '/_authenticated/kontaktlister'
      path: '/kontaktlister'
      fullPath: '/kontaktlister'
      preLoaderRoute: typeof AuthenticatedKontaktlisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/konkurrenter': {
      id: '/_authenticated/konkurrenter'
      path: '/konkurrenter'
      fullPath: '/konkurrenter'
      preLoaderRoute: typeof AuthenticatedKonkurrenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aftaler/': {
      id: '/_authenticated/aftaler/'
      path: '/aftaler'
      fullPath: '/aftaler/'
      preLoaderRoute: typeof AuthenticatedAftalerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/virksomheder_/$id': {
      id: '/_authenticated/virksomheder_/$id'
      path: '/virksomheder/$id'
      fullPath: '/virksomheder/$id'
      preLoaderRoute: typeof AuthenticatedVirksomhederIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kontaktlister_/$id': {
      id: '/_authenticated/kontaktlister_/$id'
      path: '/kontaktlister/$id'
      fullPath: '/kontaktlister/$id'
      preLoaderRoute: typeof AuthenticatedKontaktlisterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aftaler/$id': {
      id: '/_authenticated/aftaler/$id'
      path: '/aftaler/$id'
      fullPath: '/aftaler/$id'
      preLoaderRoute: typeof AuthenticatedAftalerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/overblik': {
      id: '/_authenticated/admin/overblik'
      path: '/admin/overblik'
      fullPath: '/admin/overblik'
      preLoaderRoute: typeof AuthenticatedAdminOverblikRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/importhistorik': {
      id: '/_authenticated/admin/importhistorik'
      path: '/admin/importhistorik'
      fullPath: '/admin/importhistorik'
      preLoaderRoute: typeof AuthenticatedAdminImporthistorikRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cvr-debug': {
      id: '/_authenticated/admin/cvr-debug'
      path: '/admin/cvr-debug'
      fullPath: '/admin/cvr-debug'
      preLoaderRoute: typeof AuthenticatedAdminCvrDebugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/brugere': {
      id: '/_authenticated/admin/brugere'
      path: '/admin/brugere'
      fullPath: '/admin/brugere'
      preLoaderRoute: typeof AuthenticatedAdminBrugereRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/import/': {
      id: '/_authenticated/admin/import/'
      path: '/'
      fullPath: '/admin/import/'
      preLoaderRoute: typeof AuthenticatedAdminImportIndexRouteImport
      parentRoute: typeof AuthenticatedAdminImportRoute
    }
    '/_authenticated/admin/import/visma': {
      id: '/_authenticated/admin/import/visma'
      path: '/visma'
      fullPath: '/admin/import/visma'
      preLoaderRoute: typeof AuthenticatedAdminImportVismaRouteImport
      parentRoute: typeof AuthenticatedAdminImportRoute
    }
    '/_authenticated/admin/import/maskindata': {
      id: '/_authenticated/admin/import/maskindata'
      path: '/maskindata'
      fullPath: '/admin/import/maskindata'
      preLoaderRoute: typeof AuthenticatedAdminImportMaskindataRouteImport
      parentRoute: typeof AuthenticatedAdminImportRoute
    }
    '/_authenticated/admin/import/cvr': {
      id: '/_authenticated/admin/import/cvr'
      path: '/cvr'
      fullPath: '/admin/import/cvr'
      preLoaderRoute: typeof AuthenticatedAdminImportCvrRouteImport
      parentRoute: typeof AuthenticatedAdminImportRoute
    }
    '/_authenticated/admin/import/anden': {
      id: '/_authenticated/admin/import/anden'
      path: '/anden'
      fullPath: '/admin/import/anden'
      preLoaderRoute: typeof AuthenticatedAdminImportAndenRouteImport
      parentRoute: typeof AuthenticatedAdminImportRoute
    }
    '/_authenticated/admin/import/aftale-emner': {
      id: '/_authenticated/admin/import/aftale-emner'
      path: '/aftale-emner'
      fullPath: '/admin/import/aftale-emner'
      preLoaderRoute: typeof AuthenticatedAdminImportAftaleEmnerRouteImport
      parentRoute: typeof AuthenticatedAdminImportRoute
    }
  }
}

interface AuthenticatedAdminImportRouteChildren {
  AuthenticatedAdminImportAftaleEmnerRoute: typeof AuthenticatedAdminImportAftaleEmnerRoute
  AuthenticatedAdminImportAndenRoute: typeof AuthenticatedAdminImportAndenRoute
  AuthenticatedAdminImportCvrRoute: typeof AuthenticatedAdminImportCvrRoute
  AuthenticatedAdminImportMaskindataRoute: typeof AuthenticatedAdminImportMaskindataRoute
  AuthenticatedAdminImportVismaRoute: typeof AuthenticatedAdminImportVismaRoute
  AuthenticatedAdminImportIndexRoute: typeof AuthenticatedAdminImportIndexRoute
}

const AuthenticatedAdminImportRouteChildren: AuthenticatedAdminImportRouteChildren =
  {
    AuthenticatedAdminImportAftaleEmnerRoute:
      AuthenticatedAdminImportAftaleEmnerRoute,
    AuthenticatedAdminImportAndenRoute: AuthenticatedAdminImportAndenRoute,
    AuthenticatedAdminImportCvrRoute: AuthenticatedAdminImportCvrRoute,
    AuthenticatedAdminImportMaskindataRoute:
      AuthenticatedAdminImportMaskindataRoute,
    AuthenticatedAdminImportVismaRoute: AuthenticatedAdminImportVismaRoute,
    AuthenticatedAdminImportIndexRoute: AuthenticatedAdminImportIndexRoute,
  }

const AuthenticatedAdminImportRouteWithChildren =
  AuthenticatedAdminImportRoute._addFileChildren(
    AuthenticatedAdminImportRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKonkurrenterRoute: typeof AuthenticatedKonkurrenterRoute
  AuthenticatedKontaktlisterRoute: typeof AuthenticatedKontaktlisterRoute
  AuthenticatedSalgsintelligensRoute: typeof AuthenticatedSalgsintelligensRoute
  AuthenticatedSalgsmulighederRoute: typeof AuthenticatedSalgsmulighederRoute
  AuthenticatedVirksomhederRoute: typeof AuthenticatedVirksomhederRoute
  AuthenticatedAdminBrugereRoute: typeof AuthenticatedAdminBrugereRoute
  AuthenticatedAdminCvrDebugRoute: typeof AuthenticatedAdminCvrDebugRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRouteWithChildren
  AuthenticatedAdminImporthistorikRoute: typeof AuthenticatedAdminImporthistorikRoute
  AuthenticatedAdminOverblikRoute: typeof AuthenticatedAdminOverblikRoute
  AuthenticatedAftalerIdRoute: typeof AuthenticatedAftalerIdRoute
  AuthenticatedKontaktlisterIdRoute: typeof AuthenticatedKontaktlisterIdRoute
  AuthenticatedVirksomhederIdRoute: typeof AuthenticatedVirksomhederIdRoute
  AuthenticatedAftalerIndexRoute: typeof AuthenticatedAftalerIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKonkurrenterRoute: AuthenticatedKonkurrenterRoute,
  AuthenticatedKontaktlisterRoute: AuthenticatedKontaktlisterRoute,
  AuthenticatedSalgsintelligensRoute: AuthenticatedSalgsintelligensRoute,
  AuthenticatedSalgsmulighederRoute: AuthenticatedSalgsmulighederRoute,
  AuthenticatedVirksomhederRoute: AuthenticatedVirksomhederRoute,
  AuthenticatedAdminBrugereRoute: AuthenticatedAdminBrugereRoute,
  AuthenticatedAdminCvrDebugRoute: AuthenticatedAdminCvrDebugRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRouteWithChildren,
  AuthenticatedAdminImporthistorikRoute: AuthenticatedAdminImporthistorikRoute,
  AuthenticatedAdminOverblikRoute: AuthenticatedAdminOverblikRoute,
  AuthenticatedAftalerIdRoute: AuthenticatedAftalerIdRoute,
  AuthenticatedKontaktlisterIdRoute: AuthenticatedKontaktlisterIdRoute,
  AuthenticatedVirksomhederIdRoute: AuthenticatedVirksomhederIdRoute,
  AuthenticatedAftalerIndexRoute: AuthenticatedAftalerIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
